% LIPMSTATESPACE Generates State Space Model for 3D LIPM
%
% Course:       ECE 682 (Fall 2011)
%               Multivariate Control Systems
%
% Author:       Safwan Choudhury, MASc
%               University of Waterloo
%
% See also:     DESIGNSTATEFEEDBACK

% Email:        schoudhu@uwaterloo.ca
% Website:      http://ece.uwaterloo.ca/~schoudhu

%% State Space Names
States = {'x', 'xd', 'xdd', 'y', 'yd', 'ydd'};
Inputs = {'T_x','T_y'};
Outputs = {'ZMP_x', 'ZMP_y'};

%% State Space Matrices
A = [...
    0       1       0       0       0       0; ...
    0       0       1       0       0       0; ...
    g/zc    0       0       0       0       0; ...
    0       0       0       0       1       0; ...
    0       0       0       0       0       1; ...
    0       0       0       g/zc    0       0; ...
    ];

B = [...
    0               0;              ...
    0               0;              ...
    0               1/(m*zc);     ...
    0               0;              ...
    0               0;              ...
    -1/(m*zc)       0;              ...
    ];

C = [...
    1       0       -zc/g       0       0       0;          ...
    0       0       0           1       0       -zc/g;    ...
    ];

D = zeros(2);